/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javakhachsan;

import ConnectDB.ConnectDB;
import java.sql.*;

/**
 *
 * @author trang.nguyen
 */
public class Bill extends javax.swing.JFrame {
    Connection conn = null;
    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
        conn =  ConnectDB.getConnect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayDen = new javax.swing.JTextField();
        txtMaHoaDon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaDichVu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoNgay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        txtNgayDi = new javax.swing.JTextField();
        txtTong = new javax.swing.JTextField();
        txtTienPhong = new javax.swing.JTextField();
        txtTienDichVu = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        cbbHTTT = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        jLabel3.setText("Mã Dịch Vụ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 60, 14);
        getContentPane().add(txtNgayDen);
        txtNgayDen.setBounds(110, 150, 150, 30);
        getContentPane().add(txtMaHoaDon);
        txtMaHoaDon.setBounds(110, 40, 150, 30);

        jLabel5.setText("Mã Hóa Đơn");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 50, 59, 14);
        getContentPane().add(txtMaDichVu);
        txtMaDichVu.setBounds(110, 90, 150, 30);

        jLabel4.setText("Mã khách hàng");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 100, 72, 14);

        jLabel6.setText("Mã phòng");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 160, 60, 20);

        jLabel7.setText("Ngày đến");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 160, 60, 14);
        getContentPane().add(txtMaNhanVien);
        txtMaNhanVien.setBounds(390, 40, 150, 30);

        jLabel8.setText("Ngày đi");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 220, 50, 14);

        jLabel9.setText("Tiền Phòng");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 210, 70, 14);
        getContentPane().add(txtSoNgay);
        txtSoNgay.setBounds(110, 330, 150, 30);

        jLabel10.setText("Tiền dịch vụ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 280, 70, 14);

        jLabel11.setText("Gỉam giá KH");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 280, 56, 14);

        jLabel12.setText("Hình thức TT");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(290, 330, 70, 14);

        jLabel14.setText("Tổng tiền");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(300, 420, 45, 14);

        jLabel13.setText("Số ngày");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 330, 70, 20);
        getContentPane().add(txtMaPhong);
        txtMaPhong.setBounds(390, 150, 150, 30);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(110, 40, 150, 30);
        getContentPane().add(txtNgayDi);
        txtNgayDi.setBounds(110, 210, 150, 30);

        txtTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongActionPerformed(evt);
            }
        });
        getContentPane().add(txtTong);
        txtTong.setBounds(390, 410, 150, 30);
        getContentPane().add(txtTienPhong);
        txtTienPhong.setBounds(390, 210, 150, 30);
        getContentPane().add(txtTienDichVu);
        txtTienDichVu.setBounds(390, 270, 150, 30);

        txtGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtGiamGia);
        txtGiamGia.setBounds(110, 270, 150, 30);

        cbbHTTT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Money", "Bank Card" }));
        getContentPane().add(cbbHTTT);
        cbbHTTT.setBounds(390, 320, 90, 30);

        jLabel15.setText("Mã Nhân Viên");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 50, 70, 14);
        getContentPane().add(txtMaKhachHang);
        txtMaKhachHang.setBounds(390, 90, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bill1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 551, 580);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(390, 40, 150, 30);

        jTextField18.setText("jTextField18");
        getContentPane().add(jTextField18);
        jTextField18.setBounds(390, 100, 65, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongActionPerformed

    private void txtGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbHTTT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaDichVu;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtSoNgay;
    private javax.swing.JTextField txtTienDichVu;
    private javax.swing.JTextField txtTienPhong;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
