/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javakhachsan;

import javax.swing.JOptionPane;

/**
 *
 * @author thinh.nguyen
 */
public class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    public GiaoDien() {
        initComponents();
        this.setSize(800, 500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TfUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BCancel = new javax.swing.JButton();
        JPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(null);

        btLogin.setBackground(new java.awt.Color(255, 102, 0));
        btLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btLogin.setMnemonic('l');
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        btLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btLoginKeyPressed(evt);
            }
        });
        getContentPane().add(btLogin);
        btLogin.setBounds(510, 380, 110, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/users.png"))); // NOI18N
        jLabel2.setText("User:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 260, 120, 30);

        TfUser.setToolTipText("");
        TfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfUserActionPerformed(evt);
            }
        });
        getContentPane().add(TfUser);
        TfUser.setBounds(490, 260, 290, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/passWord.png"))); // NOI18N
        jLabel4.setText(" PassWord: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 310, 130, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/welcom.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 0, 500, 200);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/usergroup.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 160, 260, 270);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 210, 34, 14);

        BCancel.setBackground(new java.awt.Color(255, 102, 0));
        BCancel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BCancel.setMnemonic('c');
        BCancel.setText("Cancel");
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });
        getContentPane().add(BCancel);
        BCancel.setBounds(650, 380, 110, 30);
        getContentPane().add(JPass);
        JPass.setBounds(490, 310, 290, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-130, 0, 980, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        if (TfUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập tài khoản !");
        } else if (JPass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập mật khẩu !");
        } else if (TfUser.getText().equals("KHACHSAN")) {
            if (JPass.getText().equals("NAMSAO")) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công.");
                MENU1 ql = new MENU1(); // tạo mới một đối tượng menu mới xuất ra màn hình
                ql.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Sai mật khẩu !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại !");
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        TfUser.setText("");
        JPass.setText("");


    }//GEN-LAST:event_BCancelActionPerformed

    private void btLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btLoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLoginKeyPressed

    private void TfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancel;
    private javax.swing.JPasswordField JPass;
    private javax.swing.JTextField TfUser;
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
