/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javakhachsan;

import ConnectDB.ConnectDB;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.JFrame;
import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author thinh.nguyen
 */
public class ListCustomer extends javax.swing.JFrame {

    /**
     * Creates new form ListCustomer
     */
    DefaultTableModel model;
    Connection conn = null;
    private ResultSet result;

    public ListCustomer() {
        initComponents();
        this.setSize(1040, 490);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) tbListCustomer.getModel();
        conn = ConnectDB.getConnect();
        showTable();

    }

    public void showTable() {
        try {
            PreparedStatement preStatement = conn.prepareStatement("select * from KhachHang");
            //model.setRowCount(0);
            result = preStatement.executeQuery();
            while (result.next()) {
                Object[] arr = {result.getString(1),
                    result.getString(2),
                    result.getDate(3),
                    result.getString(4),
                    result.getString(5),
                    result.getString(6),
                    result.getString(7),
                    result.getString(8)};
                model.addRow(arr);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbListCustomer = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ReturnRoom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbListCustomer.setAutoCreateRowSorter(true);
        tbListCustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbListCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Nationality", "Birthday", "Address", "Phones", "Email", "RoomList", "Kind", "Price", "ID Room", "Day Arrival", "Day Leave", "Service"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbListCustomer.setToolTipText("");
        jScrollPane1.setViewportView(tbListCustomer);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 150, 1040, 210);

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        jLabel3.setText("CUSTOMER INFORMATION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 10, 420, 50);

        ReturnRoom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReturnRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        ReturnRoom.setText("RETURN");
        ReturnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnRoomActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnRoom);
        ReturnRoom.setBounds(470, 390, 140, 40);

        jLabel1.setText("Search:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 30, 60, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(830, 20, 190, 30);

        jButton1.setText("Search");
        getContentPane().add(jButton1);
        jButton1.setBounds(940, 60, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gound room.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1050, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnRoomActionPerformed
        // TODO add your handling code here:]
        ROOM ro = new ROOM();
        ro.setVisible(true);
    }//GEN-LAST:event_ReturnRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ListCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnRoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbListCustomer;
    // End of variables declaration//GEN-END:variables
}
