/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javakhachsan;

import ConnectDB.ConnectDB;
import java.awt.Color;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author thinh.nguyen
 */
public class ROOM extends javax.swing.JFrame {

    String Phong = "";
    int i = 0;

    /**
     * Creates new form ROOM
     */
    public ROOM() {
        initComponents();
        this.setSize(945, 590);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    public void setPhong() {
        JToggleButton button[] = {phong1f1, phong2f1, phong3f1, phong4f1, phong5f1, phong6f1, phong1f2, phong2f2, phong3f2, phong4f2, phong5f2, phong6f2, phong1f3, phong2f3, phong3f3, phong4f3, phong5f3, phong6f3, phong1f4, phong2f4, phong3f4, phong4f4, phong5f4, phong6f4, phong1f5, phong2f5, phong3f5, phong4f5, phong5f5, phong6f5};
        String BUTTON[] = {" phong1f1", " phong2f1", " phong3f1", " phong4f1", " phong5f1", " phong6f1", " phong1f2", " phong2f2", " phong3f2", " phong4f2", " phong5f2", " phong6f2", " phong1f3", " phong2f3", " phong3f3", " phong4f3", " phong5f3", " phong6f3", " phong1f4", " phong2f4", " phong3f4", " phong4f4", " phong5f4", " phong6f4", " phong1f5", " phong2f5", " phong3f5", " phong4f5", " phong5f5", " phong6f5"};
        //tinhtien -= 1000;
//        String s = String.valueOf(tinhtien);
//        jLabel19.setText(s);
//        jLabel15.setText(s);

        for (int k = 0; k < 30; k++) {
            if (button[k].isSelected()) {
            } else {
                Phong = Phong.replaceAll(BUTTON[k], "");
                txtPhong.setText(Phong);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phong1f1 = new javax.swing.JToggleButton();
        phong2f1 = new javax.swing.JToggleButton();
        phong3f1 = new javax.swing.JToggleButton();
        phong4f1 = new javax.swing.JToggleButton();
        phong5f1 = new javax.swing.JToggleButton();
        phong6f1 = new javax.swing.JToggleButton();
        phong1f2 = new javax.swing.JToggleButton();
        phong2f2 = new javax.swing.JToggleButton();
        phong3f2 = new javax.swing.JToggleButton();
        phong4f2 = new javax.swing.JToggleButton();
        phong5f2 = new javax.swing.JToggleButton();
        phong6f2 = new javax.swing.JToggleButton();
        phong1f3 = new javax.swing.JToggleButton();
        phong2f3 = new javax.swing.JToggleButton();
        phong3f3 = new javax.swing.JToggleButton();
        phong4f3 = new javax.swing.JToggleButton();
        phong5f3 = new javax.swing.JToggleButton();
        phong6f3 = new javax.swing.JToggleButton();
        phong1f4 = new javax.swing.JToggleButton();
        phong2f4 = new javax.swing.JToggleButton();
        phong3f4 = new javax.swing.JToggleButton();
        phong4f4 = new javax.swing.JToggleButton();
        phong5f4 = new javax.swing.JToggleButton();
        phong6f4 = new javax.swing.JToggleButton();
        phong1f5 = new javax.swing.JToggleButton();
        phong2f5 = new javax.swing.JToggleButton();
        phong3f5 = new javax.swing.JToggleButton();
        phong4f5 = new javax.swing.JToggleButton();
        phong5f5 = new javax.swing.JToggleButton();
        phong6f5 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtMenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPhong = new javax.swing.JTextField();
        btOkChon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        phong1f1.setBackground(new java.awt.Color(153, 255, 51));
        phong1f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong1f1.setText("01 - F1");
        phong1f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong1f1ActionPerformed(evt);
            }
        });
        getContentPane().add(phong1f1);
        phong1f1.setBounds(20, 110, 120, 50);

        phong2f1.setBackground(new java.awt.Color(153, 255, 51));
        phong2f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong2f1.setText("02 - F1");
        phong2f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong2f1ActionPerformed(evt);
            }
        });
        getContentPane().add(phong2f1);
        phong2f1.setBounds(170, 110, 120, 50);

        phong3f1.setBackground(new java.awt.Color(153, 255, 51));
        phong3f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong3f1.setText("03 - F1");
        phong3f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong3f1ActionPerformed(evt);
            }
        });
        getContentPane().add(phong3f1);
        phong3f1.setBounds(330, 110, 130, 50);

        phong4f1.setBackground(new java.awt.Color(153, 255, 51));
        phong4f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong4f1.setText("04 - F1");
        phong4f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong4f1ActionPerformed(evt);
            }
        });
        getContentPane().add(phong4f1);
        phong4f1.setBounds(490, 110, 120, 50);

        phong5f1.setBackground(new java.awt.Color(153, 255, 51));
        phong5f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong5f1.setText("05 - F1");
        phong5f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong5f1ActionPerformed(evt);
            }
        });
        getContentPane().add(phong5f1);
        phong5f1.setBounds(640, 110, 120, 50);

        phong6f1.setBackground(new java.awt.Color(153, 255, 51));
        phong6f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong6f1.setText("06 - F1");
        phong6f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong6f1ActionPerformed(evt);
            }
        });
        getContentPane().add(phong6f1);
        phong6f1.setBounds(790, 110, 120, 50);

        phong1f2.setBackground(new java.awt.Color(153, 255, 51));
        phong1f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong1f2.setText("01 - F2");
        phong1f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong1f2ActionPerformed(evt);
            }
        });
        getContentPane().add(phong1f2);
        phong1f2.setBounds(20, 180, 120, 50);

        phong2f2.setBackground(new java.awt.Color(153, 255, 51));
        phong2f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong2f2.setText("02 - F2");
        phong2f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong2f2ActionPerformed(evt);
            }
        });
        getContentPane().add(phong2f2);
        phong2f2.setBounds(170, 180, 120, 50);

        phong3f2.setBackground(new java.awt.Color(153, 255, 51));
        phong3f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong3f2.setText("03 - F2");
        phong3f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong3f2ActionPerformed(evt);
            }
        });
        getContentPane().add(phong3f2);
        phong3f2.setBounds(330, 180, 130, 50);

        phong4f2.setBackground(new java.awt.Color(153, 255, 51));
        phong4f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong4f2.setText("04 - F2");
        phong4f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong4f2ActionPerformed(evt);
            }
        });
        getContentPane().add(phong4f2);
        phong4f2.setBounds(490, 180, 120, 50);

        phong5f2.setBackground(new java.awt.Color(153, 255, 51));
        phong5f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong5f2.setText("05 - F2");
        phong5f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong5f2ActionPerformed(evt);
            }
        });
        getContentPane().add(phong5f2);
        phong5f2.setBounds(640, 180, 120, 50);

        phong6f2.setBackground(new java.awt.Color(153, 255, 51));
        phong6f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong6f2.setText("06 - F2");
        phong6f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong6f2ActionPerformed(evt);
            }
        });
        getContentPane().add(phong6f2);
        phong6f2.setBounds(790, 180, 120, 50);

        phong1f3.setBackground(new java.awt.Color(153, 255, 51));
        phong1f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong1f3.setText("01 - F3");
        phong1f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong1f3ActionPerformed(evt);
            }
        });
        getContentPane().add(phong1f3);
        phong1f3.setBounds(20, 290, 120, 50);

        phong2f3.setBackground(new java.awt.Color(153, 255, 51));
        phong2f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong2f3.setText("02 - F3");
        phong2f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong2f3ActionPerformed(evt);
            }
        });
        getContentPane().add(phong2f3);
        phong2f3.setBounds(170, 290, 120, 50);

        phong3f3.setBackground(new java.awt.Color(153, 255, 51));
        phong3f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong3f3.setText("03 - F3");
        phong3f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong3f3ActionPerformed(evt);
            }
        });
        getContentPane().add(phong3f3);
        phong3f3.setBounds(330, 290, 130, 50);

        phong4f3.setBackground(new java.awt.Color(153, 255, 51));
        phong4f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong4f3.setText("04 - F3");
        phong4f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong4f3ActionPerformed(evt);
            }
        });
        getContentPane().add(phong4f3);
        phong4f3.setBounds(490, 290, 120, 50);

        phong5f3.setBackground(new java.awt.Color(153, 255, 51));
        phong5f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong5f3.setText("05 - F3");
        phong5f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong5f3ActionPerformed(evt);
            }
        });
        getContentPane().add(phong5f3);
        phong5f3.setBounds(640, 290, 120, 50);

        phong6f3.setBackground(new java.awt.Color(153, 255, 51));
        phong6f3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong6f3.setText("06 - F3");
        phong6f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong6f3ActionPerformed(evt);
            }
        });
        getContentPane().add(phong6f3);
        phong6f3.setBounds(790, 290, 120, 50);

        phong1f4.setBackground(new java.awt.Color(153, 255, 51));
        phong1f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong1f4.setText("01 - F4");
        phong1f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong1f4ActionPerformed(evt);
            }
        });
        getContentPane().add(phong1f4);
        phong1f4.setBounds(20, 360, 120, 50);

        phong2f4.setBackground(new java.awt.Color(153, 255, 51));
        phong2f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong2f4.setText("02 - F4");
        phong2f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong2f4ActionPerformed(evt);
            }
        });
        getContentPane().add(phong2f4);
        phong2f4.setBounds(170, 360, 120, 50);

        phong3f4.setBackground(new java.awt.Color(153, 255, 51));
        phong3f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong3f4.setText("03 - F4");
        phong3f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong3f4ActionPerformed(evt);
            }
        });
        getContentPane().add(phong3f4);
        phong3f4.setBounds(330, 360, 130, 50);

        phong4f4.setBackground(new java.awt.Color(153, 255, 51));
        phong4f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong4f4.setText("04 - F4");
        phong4f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong4f4ActionPerformed(evt);
            }
        });
        getContentPane().add(phong4f4);
        phong4f4.setBounds(490, 360, 120, 50);

        phong5f4.setBackground(new java.awt.Color(153, 255, 51));
        phong5f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong5f4.setText("05 - F4");
        phong5f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong5f4ActionPerformed(evt);
            }
        });
        getContentPane().add(phong5f4);
        phong5f4.setBounds(640, 360, 120, 50);

        phong6f4.setBackground(new java.awt.Color(153, 255, 51));
        phong6f4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong6f4.setText("06 - F4");
        phong6f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong6f4ActionPerformed(evt);
            }
        });
        getContentPane().add(phong6f4);
        phong6f4.setBounds(790, 360, 120, 50);

        phong1f5.setBackground(new java.awt.Color(153, 255, 51));
        phong1f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong1f5.setText("01 - F5");
        phong1f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong1f5ActionPerformed(evt);
            }
        });
        getContentPane().add(phong1f5);
        phong1f5.setBounds(20, 430, 120, 50);

        phong2f5.setBackground(new java.awt.Color(153, 255, 51));
        phong2f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong2f5.setText("02 - F5");
        phong2f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong2f5ActionPerformed(evt);
            }
        });
        getContentPane().add(phong2f5);
        phong2f5.setBounds(170, 430, 120, 50);

        phong3f5.setBackground(new java.awt.Color(153, 255, 51));
        phong3f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong3f5.setText("03 - F5");
        phong3f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong3f5ActionPerformed(evt);
            }
        });
        getContentPane().add(phong3f5);
        phong3f5.setBounds(330, 430, 130, 50);

        phong4f5.setBackground(new java.awt.Color(153, 255, 51));
        phong4f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong4f5.setText("04 - F5");
        phong4f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong4f5ActionPerformed(evt);
            }
        });
        getContentPane().add(phong4f5);
        phong4f5.setBounds(490, 430, 120, 50);

        phong5f5.setBackground(new java.awt.Color(153, 255, 51));
        phong5f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong5f5.setText("05 - F5");
        phong5f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong5f5ActionPerformed(evt);
            }
        });
        getContentPane().add(phong5f5);
        phong5f5.setBounds(640, 430, 120, 50);

        phong6f5.setBackground(new java.awt.Color(153, 255, 51));
        phong6f5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/room.png"))); // NOI18N
        phong6f5.setText("06 - F5");
        phong6f5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phong6f5ActionPerformed(evt);
            }
        });
        getContentPane().add(phong6f5);
        phong6f5.setBounds(790, 430, 120, 50);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Standrad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 50, 160, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Suite");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 240, 130, 30);

        BtMenu.setText("MENU");
        BtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BtMenu);
        BtMenu.setBounds(20, 520, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Choose: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(590, 520, 60, 30);
        getContentPane().add(txtPhong);
        txtPhong.setBounds(650, 520, 210, 30);

        btOkChon.setText("OK");
        btOkChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkChonActionPerformed(evt);
            }
        });
        getContentPane().add(btOkChon);
        btOkChon.setBounds(870, 520, 60, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 520, 200, 30);

        btList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btList.setText("List");
        btList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListActionPerformed(evt);
            }
        });
        getContentPane().add(btList);
        btList.setBounds(150, 520, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gound room.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phong1f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong1f1ActionPerformed
        // TODO add your handling code here:
        if (phong1f1.isSelected()) {
            phong1f1.setBackground(new Color(0, 153, 0));
            Phong += " phong1f1";
            txtPhong.setText(Phong);
        } else {
            phong1f1.setBackground(new Color(153, 255, 51));
            setPhong();

        }


    }//GEN-LAST:event_phong1f1ActionPerformed

    private void phong2f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong2f1ActionPerformed
        // TODO add your handling code here:
        if (phong2f1.isSelected()) {
            phong2f1.setBackground(new Color(0, 153, 0));
            Phong += " phong2f1";
            txtPhong.setText(Phong);
        } else {
            phong2f1.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong2f1ActionPerformed

    private void phong3f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong3f1ActionPerformed
        // TODO add your handling code here:
        if (phong3f1.isSelected()) {
            phong3f1.setBackground(new Color(0, 153, 0));
            Phong += " phong3f1";
            txtPhong.setText(Phong);
        } else {
            phong3f1.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong3f1ActionPerformed

    private void phong4f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong4f1ActionPerformed
        // TODO add your handling code here:
        if (phong4f1.isSelected()) {
            phong4f1.setBackground(new Color(0, 153, 0));
            Phong += " phong4f1";
            txtPhong.setText(Phong);
        } else {
            phong4f1.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong4f1ActionPerformed

    private void phong5f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong5f1ActionPerformed
        // TODO add your handling code here:
        if (phong5f1.isSelected()) {
            phong5f1.setBackground(new Color(0, 153, 0));
            Phong += " phong5f1";
            txtPhong.setText(Phong);
        } else {
            phong5f1.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong5f1ActionPerformed

    private void phong6f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong6f1ActionPerformed
        // TODO add your handling code here:
        if (phong6f1.isSelected()) {
            phong6f1.setBackground(new Color(0, 153, 0));
            Phong += " phong6f1";
            txtPhong.setText(Phong);
        } else {
            phong6f1.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong6f1ActionPerformed

    private void phong3f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong3f2ActionPerformed
        // TODO add your handling code here:
        if (phong3f2.isSelected()) {
            phong3f2.setBackground(new Color(0, 153, 0));
            Phong += " phong3f2";
            txtPhong.setText(Phong);
        } else {
            phong3f2.setBackground(new Color(153, 255, 51));
            setPhong();
        }

    }//GEN-LAST:event_phong3f2ActionPerformed

    private void phong1f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong1f2ActionPerformed
        // TODO add your handling code here:
        if (phong1f2.isSelected()) {
            phong1f2.setBackground(new Color(0, 153, 0));
            Phong += " phong1f2";
            txtPhong.setText(Phong);
        } else {
            phong1f2.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong1f2ActionPerformed

    private void phong2f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong2f2ActionPerformed
        // TODO add your handling code here:
        if (phong2f2.isSelected()) {
            phong2f2.setBackground(new Color(0, 153, 0));
            Phong += " phong2f2";
            txtPhong.setText(Phong);
        } else {
            phong2f2.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong2f2ActionPerformed

    private void phong4f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong4f2ActionPerformed
        // TODO add your handling code here:
        if (phong4f2.isSelected()) {
            phong4f2.setBackground(new Color(0, 153, 0));
            Phong += " phong4f2";
            txtPhong.setText(Phong);
        } else {
            phong4f2.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong4f2ActionPerformed

    private void phong5f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong5f2ActionPerformed
        // TODO add your handling code here:
        if (phong5f2.isSelected()) {
            phong5f2.setBackground(new Color(0, 153, 0));
            Phong += " phong5f2";
            txtPhong.setText(Phong);
        } else {
            phong5f2.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong5f2ActionPerformed

    private void phong6f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong6f2ActionPerformed
        // TODO add your handling code here:
        if (phong6f2.isSelected()) {
            phong6f2.setBackground(new Color(0, 153, 0));
            Phong += " phong6f2";
            txtPhong.setText(Phong);
        } else {
            phong6f2.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong6f2ActionPerformed

    private void phong3f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong3f3ActionPerformed
        // TODO add your handling code here:
        if (phong3f3.isSelected()) {
            phong3f3.setBackground(new Color(0, 153, 0));
            Phong += " phong3f3";
            txtPhong.setText(Phong);
        } else {
            phong3f3.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong3f3ActionPerformed

    private void phong1f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong1f3ActionPerformed
        // TODO add your handling code here:
        if (phong1f3.isSelected()) {
            phong1f3.setBackground(new Color(0, 153, 0));
            Phong += " phong1f3";
            txtPhong.setText(Phong);
        } else {
            phong1f3.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong1f3ActionPerformed

    private void phong2f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong2f4ActionPerformed
        // TODO add your handling code here:
        if (phong2f4.isSelected()) {
            phong2f4.setBackground(new Color(0, 153, 0));
            Phong += " phong2f4";
            txtPhong.setText(Phong);
        } else {
            phong2f4.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong2f4ActionPerformed

    private void phong1f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong1f4ActionPerformed
        // TODO add your handling code here:
        if (phong1f4.isSelected()) {
            phong1f4.setBackground(new Color(0, 153, 0));
            Phong += " phong1f4";
            txtPhong.setText(Phong);
        } else {
            phong1f4.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong1f4ActionPerformed

    private void phong3f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong3f4ActionPerformed
        // TODO add your handling code here:
        if (phong3f4.isSelected()) {
            phong3f4.setBackground(new Color(0, 153, 0));
            Phong += " phong3f4";
            txtPhong.setText(Phong);
        } else {
            phong3f4.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong3f4ActionPerformed

    private void phong4f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong4f4ActionPerformed
        // TODO add your handling code here:
        if (phong4f4.isSelected()) {
            phong4f4.setBackground(new Color(0, 153, 0));
            Phong += " phong4f4";
            txtPhong.setText(Phong);
        } else {
            phong4f4.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong4f4ActionPerformed

    private void phong5f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong5f4ActionPerformed
        // TODO add your handling code here:
        if (phong5f4.isSelected()) {
            phong5f4.setBackground(new Color(0, 153, 0));
            Phong += " phong5f4";
            txtPhong.setText(Phong);
        } else {
            phong5f4.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong5f4ActionPerformed

    private void phong6f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong6f4ActionPerformed
        // TODO add your handling code here:
        if (phong6f4.isSelected()) {
            phong6f4.setBackground(new Color(0, 153, 0));
            Phong += " phong6f4";
            txtPhong.setText(Phong);
        } else {
            phong6f4.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong6f4ActionPerformed

    private void phong2f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong2f3ActionPerformed
        // TODO add your handling code here:
        if (phong2f3.isSelected()) {
            phong2f3.setBackground(new Color(0, 153, 0));
            Phong += " phong2f3";
            txtPhong.setText(Phong);
        } else {
            phong2f3.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong2f3ActionPerformed

    private void phong4f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong4f3ActionPerformed
        // TODO add your handling code here:
        if (phong4f3.isSelected()) {
            phong4f3.setBackground(new Color(0, 153, 0));
            Phong += " phong4f3";
            txtPhong.setText(Phong);
        } else {
            phong4f3.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong4f3ActionPerformed

    private void phong5f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong5f3ActionPerformed
        // TODO add your handling code here:
        if (phong5f3.isSelected()) {
            phong5f3.setBackground(new Color(0, 153, 0));
            Phong += " phong5f3";
            txtPhong.setText(Phong);
        } else {
            phong5f3.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong5f3ActionPerformed

    private void phong6f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong6f3ActionPerformed
        // TODO add your handling code here:
        if (phong6f3.isSelected()) {
            phong6f3.setBackground(new Color(0, 153, 0));
            Phong += " phong6f3";
            txtPhong.setText(Phong);
        } else {
            phong6f3.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong6f3ActionPerformed

    private void phong1f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong1f5ActionPerformed
        // TODO add your handling code here:
        if (phong1f5.isSelected()) {
            phong1f5.setBackground(new Color(0, 153, 0));
            Phong += " phong1f5";
            txtPhong.setText(Phong);
        } else {
            phong1f5.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong1f5ActionPerformed

    private void phong2f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong2f5ActionPerformed
        // TODO add your handling code here:
        if (phong2f5.isSelected()) {
            phong2f5.setBackground(new Color(0, 153, 0));
            Phong += " phong2f5";
            txtPhong.setText(Phong);
        } else {
            phong2f5.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong2f5ActionPerformed

    private void phong3f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong3f5ActionPerformed
        // TODO add your handling code here:
        if (phong3f5.isSelected()) {
            phong3f5.setBackground(new Color(0, 153, 0));
            Phong += " phong3f5";
            txtPhong.setText(Phong);
        } else {
            phong3f5.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong3f5ActionPerformed

    private void phong4f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong4f5ActionPerformed
        // TODO add your handling code here:
        if (phong4f5.isSelected()) {
            phong4f5.setBackground(new Color(0, 153, 0));
            Phong += " phong4f5";
            txtPhong.setText(Phong);
        } else {
            phong4f5.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong4f5ActionPerformed

    private void phong5f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong5f5ActionPerformed
        // TODO add your handling code here:
        if (phong5f5.isSelected()) {
            phong5f5.setBackground(new Color(0, 153, 0));
            Phong += " phong5f5";
            txtPhong.setText(Phong);
        } else {
            phong5f5.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong5f5ActionPerformed

    private void phong6f5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phong6f5ActionPerformed
        // TODO add your handling code here:
        if (phong6f5.isSelected()) {
            phong6f5.setBackground(new Color(0, 153, 0));
            Phong += " phong6f5";
            txtPhong.setText(Phong);
        } else {
            phong6f5.setBackground(new Color(153, 255, 51));
            setPhong();
        }
    }//GEN-LAST:event_phong6f5ActionPerformed

    private void BtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMenuActionPerformed
        // TODO add your handling code here:
        MENU1 menu = new MENU1();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtMenuActionPerformed

    private void btOkChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkChonActionPerformed
        // TODO add your handling code here:
        ConnectDB connect = new ConnectDB();
        
        JToggleButton button[] = {phong1f1, phong2f1, phong3f1, phong4f1, phong5f1, phong6f1, phong1f2, phong2f2, phong3f2, phong4f2, phong5f2, phong6f2, phong1f3, phong2f3, phong3f3, phong4f3, phong5f3, phong6f3, phong1f4, phong2f4, phong3f4, phong4f4, phong5f4, phong6f4, phong1f5, phong2f5, phong3f5, phong4f5, phong5f5, phong6f5};
       for (i = 0; i < 30; i++) {
            if (button[i].isSelected()) {
                button[i].setEnabled(false);
                Phong = "";
                txtPhong.setText(Phong);
                try {
                    String sql = "insert into Phong values(?)";
                    PreparedStatement preStatement = connect.getConnect().prepareStatement(sql);
                    preStatement.setString(1, button[i].getText());
//                    int x = preStatement.executeUpdate();
//                    if (x > 0) {
//                       JOptionPane.showMessageDialog(null, "Thêm danh sách thành công");
//
//                   }
                } catch (Exception ex) {
                    ex.printStackTrace();
        
                }
            }
       }
    }//GEN-LAST:event_btOkChonActionPerformed

    private void btListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListActionPerformed
        // TODO add your handling code here:
        DanhsachKhachHang ds = new DanhsachKhachHang(Phong);
        ds.setVisible(true);
        ds.setSize(600, 400);
        ds.setResizable(false);
    }//GEN-LAST:event_btListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ROOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ROOM().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtMenu;
    private javax.swing.JButton btList;
    private javax.swing.JButton btOkChon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JToggleButton phong1f1;
    public javax.swing.JToggleButton phong1f2;
    public javax.swing.JToggleButton phong1f3;
    public javax.swing.JToggleButton phong1f4;
    public javax.swing.JToggleButton phong1f5;
    public javax.swing.JToggleButton phong2f1;
    public javax.swing.JToggleButton phong2f2;
    public javax.swing.JToggleButton phong2f3;
    public javax.swing.JToggleButton phong2f4;
    public javax.swing.JToggleButton phong2f5;
    public javax.swing.JToggleButton phong3f1;
    public javax.swing.JToggleButton phong3f2;
    public javax.swing.JToggleButton phong3f3;
    public javax.swing.JToggleButton phong3f4;
    public javax.swing.JToggleButton phong3f5;
    public javax.swing.JToggleButton phong4f1;
    public javax.swing.JToggleButton phong4f2;
    public javax.swing.JToggleButton phong4f3;
    public javax.swing.JToggleButton phong4f4;
    public javax.swing.JToggleButton phong4f5;
    public javax.swing.JToggleButton phong5f1;
    public javax.swing.JToggleButton phong5f2;
    public javax.swing.JToggleButton phong5f3;
    public javax.swing.JToggleButton phong5f4;
    public javax.swing.JToggleButton phong5f5;
    public javax.swing.JToggleButton phong6f1;
    public javax.swing.JToggleButton phong6f2;
    public javax.swing.JToggleButton phong6f3;
    public javax.swing.JToggleButton phong6f4;
    public javax.swing.JToggleButton phong6f5;
    public javax.swing.JTextField txtPhong;
    // End of variables declaration//GEN-END:variables
}
